name: Build Debian Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper devscripts rsync

    - name: Build package
      run: dpkg-buildpackage -us -uc -b

    - name: Upload to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ../pinballux_*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
